apiVersion: v1
kind: Service
metadata:
  name: vehiclemiles-service
  labels:
    name: vehiclemiles-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30072
      name: vehiclemiles-port
  selector:
    app: vehiclemiles
  type: NodePort 

